config/routes.rb
Rails.application.routes.draw do  
  devise_for :users

  root "static_pages#home"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"

  namespace :admin do
    root "static_pages#home"
    get "projects/get_user_by_team/:team_id" => "projects#index"
    
    resources :positions, except: [:show, :new]
    resources :skills, except: [:show, :new]
    resources :activities, only: [:index, :destroy]
    resources :teams
    resources :users
    resources :projects
    resources :imports, only: [:create]
  end

  resources :users, only: [:show, :update] do
    resources :skill_users, only: :show
    match "/add_skill", to: "skill_users#show", via: :get
  end  
  resources :teams, only: [:index, :show]
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  include ActivityLog
  extend ExportCsv

  has_many :skill_users, dependent: :destroy
  has_many :users, through: :skill_users

  validates :name, presence: true, uniqueness: {case_sensitive: false}

  after_create :log_create
  after_update :log_update
  after_destroy :log_delete

  def self.get_id skill_name
    Skill.find_by(name: skill_name).id
  end

  def self.import_csv file
    CSV.foreach file.path, headers: true, header_converters: :downcase do |row|
      record = Skill.find_by(name: row["skill"]) || Skill.new
      record.attributes = row.to_hash.slice "skill"
      record.save!
    end
  end
end

app/controllers/admin/skills_controller.rb
class Admin::SkillsController < Admin::BaseAdminController
  def index
    @skills = @skills.paginate page: params[:page], per_page:
                                   Settings.general.per_page
    @skill = Skill.new
    respond_to do |format|
      format.html
      format.csv {send_data @skills.as_csv}
    end
  end  

  def create
    if @skill.save
      flash[:success] = t "skill.create_success"
    else
      flash[:danger] = t "skill.create_fail"
    end
    redirect_to admin_skills_url
  end

  def edit
  end

  def update
    if @skill.update_attributes skill_params
      flash[:success] = t "skill.update_success"
    else
      flash[:danger] = t "skill.update_fail"
    end
    redirect_to admin_skills_url
  end

  def destroy
    @skill.destroy
    flash[:success] = t "skill.delete_success"
    redirect_to admin_skills_url
  end

  private
  def skill_params
    params.require(:skill).permit :name
  end
end

app/views/admin/skills/_form.html.erb
<%= form_for [:admin, @skill] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  
  <div class="field">
    <%= f.label t "general.name" %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="controls">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/admin/skills/_skill.html.erb
<tr>
  <td><%= skill.id %></td>
  <td><%= skill.name %></td>
  <td><%= link_to "", edit_admin_skill_path(skill), 
                      class: "glyphicon glyphicon-edit" %></td>
  <td><%= link_to "", [:admin, skill], class: "glyphicon glyphicon-trash",
          method: :delete, data: {confirm: t("general.confirm_delete")} %></td>
                      
</tr>

app/views/admin/skills/edit.html.erb
<% provide :title, t("skill.title_edit") %>
<h1><%= t "skill.title_edit" %></h1>
<div class="col-md-6 col-md-offset-3">
  <%= render "form" %>
</div>

app/views/admin/skills/index.html.erb
<% provide :title, t("skill.all_skills") %>
<h1><%= t "skill.create_skill" %></h1>
<div class="col-md-6 col-md-offset-3">
  <%= render "shared/import_form", model: Skill %>
  <%= render "form" %>
</div>
<div class="skills col-md-8 col-md-offset-2">
  <h2><%= t "skill.all_skills" %></h2>
  <% if @skills.any? %>
    <%= t "general.download" %>  
    <%= link_to t("general.csv"), admin_skills_path(format: :csv) %>
    <table class="table table-striped">
      <tr>
        <th><%= t "general.id" %></th>
        <th><%= t "general.name" %></th>
        <th colspan="2"></th>
      </tr>
      <%= render partial: "skill", collection: @skills %>
    </table>
  <% else %>
    <h3><%= t "skill.no_skill" %></h3>
  <% end %>
</div>