config/routes.rb
Rails.application.routes.draw do  
  devise_for :users

  root "static_pages#home"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"

  namespace :admin do
    root "static_pages#home"
    get "projects/get_user_by_team/:team_id" => "projects#index"
    
    resources :positions, except: [:show, :new]
    resources :skills, except: [:show, :new]
    resources :activities, only: [:index, :destroy]
    resources :teams
    resources :users
    resources :projects
    resources :imports, only: [:create]
  end

  resources :users, only: [:show, :update] do
    resources :skill_users, only: :show
    match "/add_skill", to: "skill_users#show", via: :get
  end  
  resources :teams, only: [:index, :show]
end

app/models/position.rb
class Position < ActiveRecord::Base
  include ActivityLog
  extend ExportCsv

  has_many :users, dependent: :destroy

  validates :name, presence: true, length: {maximum: Settings.models.position.
                                                              max_length_name}
  validates :abbreviation, presence: true, length: {maximum: Settings.models.
                                            position.max_length_abbreviation}

  after_create :log_create
  after_update :log_update
  after_destroy :log_delete

  def self.import_csv file
    CSV.foreach file.path, headers: true, header_converters: :downcase do |row|
      record = Position.find_by(name: row["position"]) || Position.new
      record.attributes = row.to_hash.slice "position", "abbreviation"
      record.save!
    end
  end
end

app/controllers/admin/positions_controller.rb
class Admin::PositionsController < Admin::BaseAdminController
  def index
    @positions = @positions.paginate page: params[:page],
                                     per_page: Settings.general.per_page
    @position = Position.new
    respond_to do |format|
      format.html
      format.csv {send_data @positions.to_csv}
    end
  end

  def create
    if @position.save
      flash[:success] = t "position.create_success"
    else
      flash[:danger] = t "position.create_not_success"
    end
    redirect_to admin_positions_url
  end

  def update
    if @position.update_attributes position_params
      flash[:success] = t "position.update_success"
      redirect_to admin_positions_url
    else
      render "edit"
    end
  end
  
  def destroy
    @position.destroy
    redirect_to admin_positions_url
  end

  private
  def position_params
    params.require(:position).permit :name, :abbreviation
  end
end

app/views/admin/positions/_form.html.erb
<%= form_for [:admin, @position] do |f| %>
  <div class="fields">
    <%= f.label t "general.name" %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label t "position.abbreviation" %>
    <%= f.text_field :abbreviation, class: "form-control" %>
  </div>
  <div class="controls">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/admin/positions/_position.html.erb
<tr class="position">
  <td><%= position.id %></td>
  <td><%= position.name %></td>
  <td><%= position.abbreviation %></td>
  <td><%= link_to t("general.edit"), edit_admin_position_path(position) %></td>
  <td>
    <%= link_to t("general.delete"), [:admin, position], method: :delete, data: 
                                     {confirm: t("general.confirm_delete")} %>
  </td>
</tr>

app/views/admin/positions/edit.html.erb
<% provide :title, t("position.title_edit") %>
<h1><%= t "position.title_edit" %></h1>
<div class="col-md-6 col-md-offset-3">
  <%= render "form" %>
</div>

app/views/admin/positions/index.html.erb
<% provide :title, t("position.title_index") %>
<div class="col-md-8 col-md-offset-2">
  <%= render "shared/import_form", model: Position %>
  <div class="create_position col-md-4">
    <h2><%= t "position.create_position" %></h2>
    <%= t "general.download" %>: 
    <%= link_to t("general.csv"), admin_positions_path(format: :csv) %>
    <%= render "form" %>
  </div>  
  <div class="clearfix"></div>
  <table class="table table-striped">
    <tr>
      <th><%= t "general.id" %></th>
      <th><%= t "general.name" %></th>
      <th><%= t "position.abbreviation" %></th>
      <th colspan="2"></th>
    </tr>
    <div class="positions">
      <%= render partial: "position", collection: @positions %>
    </div>    
  </table>
  <%= will_paginate @positions %>
</div>