config/routes.rb
Rails.application.routes.draw do  
  devise_for :users

  root "static_pages#home"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"

  namespace :admin do
    root "static_pages#home"
    get "projects/get_user_by_team/:team_id" => "projects#index"
    
    resources :positions, except: [:show, :new]
    resources :skills, except: [:show, :new]
    resources :activities, only: [:index, :destroy]
    resources :teams
    resources :users
    resources :projects
    resources :imports, only: [:create]
  end

  resources :users, only: [:show, :update] do
    resources :skill_users, only: :show
    match "/add_skill", to: "skill_users#show", via: :get
  end  
  resources :teams, only: [:index, :show]
end

app/models/project.rb
class Project < ActiveRecord::Base
  include ActivityLog

  belongs_to :team
  has_many :project_users, dependent: :destroy
  has_many :users, through: :project_users
  accepts_nested_attributes_for :project_users, allow_destroy: true
  belongs_to :leader, class_name: "User"
  
  validates :name, presence: true
  validates :abbreviation, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true

  after_create :log_create
  after_update :log_update
  after_destroy :log_delete
  after_save :assign_user_project

  def to_csv
    CSV.generate do |csv|
      csv << Settings.csv.project_column
      csv << [name, abbreviation, start_date, end_date, team.name, leader.name]
      csv << Settings.csv.member
      csv << users.pluck(:name)
    end
  end

  def self.import_csv file
    attributes_hash = Hash.new{|hash, key| hash[key] = []}
    CSV.foreach file.path, headers: true, header_converters: :downcase do |row|
      t = row.to_hash.slice "name", "abbreviation", "start", "end", "member"
      t.keys.each {|key| attributes_hash[key].push t[key] unless t[key].nil?}
    end
    attributes = Hash[name: attributes_hash["name"].first, 
                      abbreviation: attributes_hash["abbreviation"].first,
                      start_date: attributes_hash["start"].first,
                      end_date: attributes_hash["end"].first,
                      user_ids: attributes_hash["member"].map{|m| User.get_id m}]
    begin
      Project.find_by(name: attributes[:name]).update_attributes attributes
    rescue
      Project.create! attributes
    end
  end

  private
  def assign_user_project
    begin
      unless users == team.users
        project_users.destroy_all
        users << team.users
      end
    rescue
    end
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseAdminController
  before_action :get_all_teams, only: [:new, :edit]

  def index
    begin
      @users = Team.find_by(id: params[:team_id]).users
      respond_to do |format|
        format.json  {render json: @users}      
      end
    rescue
      @q = Project.ransack params[:q]
      @projects = @q.result.paginate page: params[:page],
                                     per_page: Settings.general.per_page
    end
  end

  def show
    @team = @project.team
    @user = @project.leader
    respond_to do |format|
      format.html
      format.csv {send_data @project.to_csv}
    end
  end

  def create
    if @project.save
      flash[:success] = t "project.project_create"
      redirect_to admin_projects_path
    else
      render :new
    end
  end

  def edit
    @users = @project.team.users.order name: :desc
  end

  def update
    if @project.update_attributes project_params
      redirect_to admin_project_path @project
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to admin_projects_path
  end

  private
  def project_params
    params.require(:project).permit :name, :abbreviation, :team_id,
                                    :leader_id, :start_date, :end_date
  end

  def get_all_teams
    @teams = Team.order name: :desc
  end
end

app/views/admin/projects/_project.html.erb
<%= div_for project, class: "col-md-3" do %>  
  <%= link_to project.name, admin_project_path(project) %><br>
<% end %>

app/views/admin/projects/_project_form.html.erb
<%= form_for [:admin, @project] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :abbreviation %><br>
    <%= f.text_field :abbreviation, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_field :start_date, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_field :end_date, class: "form-control" %>
  </div>
  <div class="field">
    <% if @teams.present? %>
      <%= f.label :team_id %><br>
      <%= f.collection_select :team_id, @teams, :id, :name, prompt: true %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :leader_id %><br>
    <% if @users.present? %>
      <%= f.collection_select :leader_id, @users, :id, :name, prompt: true %>
    <% else %>
      <%= f.collection_select :leader_id, [], :id, :name, prompt: true %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit t "general.submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/projects/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <%= render "project_form" %>
</div>

app/views/admin/projects/index.html.erb
<% provide :title, t("project.project_list") %>
<div class="col-md-8 col-md-offset-2">
  <%= render "shared/import_form", model: Project %>
  <h1><%= t "project.project_list" %></h1>
  <%= link_to t("project.project_create"), new_admin_project_path,
                                           data: {no_turbolink: true},
                                           class: "btn btn-success btn-lg" %>
  <div class="projects"> 
    <%= search_form_for [:admin, @q] do |f| %>
      <%= f.label :team_name_cont %>
      <%= f.search_field :team_name_cont, class: "form-control",
                                          placeholder: t("user.placeholder_search") %>
      <%= f.submit class: "btn btn-success" %>
    <% end %>
    <%= render partial: "project", collection: @projects %>
    <%= will_paginate @projects %>
  </div>
</div>

app/views/admin/projects/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <%= render "project_form" %>
</div>

app/views/admin/projects/show.html.erb
<%= provide :title, @project.name %>
<h1><%= @project.name %></h1>
<div class="col-md-4">
  <%= t "general.download" %>  
  <%= link_to t("general.csv"), admin_project_path(format: :csv) %>
  <div id="content">
    <ul class="list_group">
      <li class="list-group-item list-group-item-info">
        <%= t "abbreviation" %> : <strong><%= @project.abbreviation %></strong>
      </li>
      <li class="list-group-item list-group-item-info">
        <%= t "start" %> : <strong><%= @project.start_date %></strong>
      </li>
      <li class="list-group-item list-group-item-info">
        <%= t "end" %> : 
        <% if @project.end_date.nil? %>
          <strong>In progress</strong>
        <% else %>
          <strong><%= @project.end_date %></strong>
        <% end %>
      </li>
      <li class="list-group-item list-group-item-info">
        Team : <strong><%= @team.name %></strong>
      </li>
      <% if @user.present? %>
        <li class="list-group-item list-group-item-info">
          <%= t "leader" %> : <strong><%= @user.name %></strong>
        </li>
      <% end %>
      <%= link_to t("general.edit"), edit_admin_project_path(@project),
                                     data: {no_turbolink: true},
                                     class: "btn btn-warning" %>
      <%= link_to t("general.delete"), admin_project_path(@project),
                                       method: :delete,
                                       data: {confirm: t("general.confirm_delete")},
                                       class: "btn btn-danger" %>
    </ul>
  </div>
</div>