config/routes.rb
Rails.application.routes.draw do  
  devise_for :users

  root "static_pages#home"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"

  namespace :admin do
    root "static_pages#home"
    get "projects/get_user_by_team/:team_id" => "projects#index"
    
    resources :positions, except: [:show, :new]
    resources :skills, except: [:show, :new]
    resources :activities, only: [:index, :destroy]
    resources :teams
    resources :users
    resources :projects
    resources :imports, only: [:create]
  end

  resources :users, only: [:show, :update] do
    resources :skill_users, only: :show
    match "/add_skill", to: "skill_users#show", via: :get
  end  
  resources :teams, only: [:index, :show]
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <p class="text-center">&copy; <%= t "general.footer" %></p>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <% if logged_in_admin? %>
        <%= link_to t("general.logo_admin"), root_path, class: "navbar-brand" %>
      <% else %>
        <%= link_to t("general.logo"), root_path, class: "navbar-brand" %>
      <% end %>
    </div>
    <div>
      <% if logged_in_admin? %>
        <ul class="nav navbar-nav">          
          <li><%= link_to t("general.menu_item_home"), root_path %></li>
          <li><%= link_to t("general.menu_item_users"), admin_users_path %></li>
          <li><%= link_to t("general.menu_item_teams"), admin_teams_path %></li>
          <li><%= link_to t("general.menu_item_positions"), admin_positions_path %></li>
          <li><%= link_to t("general.menu_item_projects"), admin_projects_path %></li>
          <li><%= link_to t("general.menu_item_skills"), admin_skills_path %></li>                
          <li><%= link_to t("general.menu_item_log"), admin_activities_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.name %>
            <span class="caret"></span></a>
            <ul class="dropdown-menu">            
              <li><%= link_to t("general.profile"), "#" %></li>
              <li><%= link_to t("general.setting"), edit_user_registration_path %></li>
              <li><%= link_to t("general.logout"), destroy_user_session_path,
                                                   method: :delete %></li>
            </ul>
          </li>
        </ul>
      <% elsif user_signed_in? %>                      
        <ul class="nav navbar-nav">
          <li><%= link_to t("general.menu_item_teams"), teams_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.name %><span class="caret"></span></a>
            <ul class="dropdown-menu">            
              <li><%= link_to t("general.profile"), current_user %></li>                
              <li><%= link_to t("general.logout"), destroy_user_session_path,
                                                   method: :delete %></li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav">
          <li><%= link_to t("general.menu_item_home"), root_path %></li>
          <li><%= link_to t("general.menu_item_about"), about_path %></li>
          <li><%= link_to t("general.menu_item_contact"), contact_path %></li>
        </ul> 
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to t("general.login"), new_user_session_path, id: "login" %></li>
        </ul>      
      <% end %>     
    </div>
  </div>
</nav>

app/views/layouts/_select_language.html.erb
<div class="select-language pull-right">
  <div class="clearfix"></div>
  <div class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
      <%= t "general.select_lang" %>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <% Settings.general.langs.each do |lang_key, lang_name| %>
        <li><%= link_to lang_name, url_for(locale: lang_key) %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= render "layouts/shim" %>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <%= render "layouts/header" %>
    <div class="container" id="content">
      <div class="row">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= render "layouts/select_language" %>
        <%= yield %>
      </div>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>